# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-PlaTDFU1riJGSbeyyYlABHam_eDdcP0
"""

# Задача 2.1

def maximum(arr):
    
    result = arr[0]
    for i in arr:
        if result < i:
            result = i
    return result

valuesmax = [4,6,2,1,9,63,-134,566] 
valuesmax1 = [-52, 56, 30, 29, -54, 0, -110]
valuesmax2 = [42, 54, 65, 87, 0] 
valuesmax3 = [5]

def minimum(arr):

    result = arr[0]
    for i in arr:
        if result > i:
            result = i
    return result

valuesmin = [4,6,2,1,9,63,-134,566]
valuesmin1 = [-52, 56, 30, 29, -54, 0, -110]
valuesmin2 = [42, 54, 65, 87, 0] 
valuesmin3 = [5]

print(valuesmax, "->","max =", maximum(valuesmax), "," , "min =", minimum(valuesmin))
print(valuesmax1, "->","max =", maximum(valuesmax1), "," , "min =", minimum(valuesmin1))
print(valuesmax2, "->","max =", maximum(valuesmax2), "," , "min =", minimum(valuesmin2))
print(valuesmax3, "->","max =", maximum(valuesmax3), "," , "min =", minimum(valuesmin3))