# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HTBMSkG-c89a-riaqpTJ5WYV8qFYmKXj
"""

# Задача 2.4.

#Пункт A.

def remove_exclamation_marks(s):
  return s.replace('!','')
print(remove_exclamation_marks("Hi! Hello!"))

# Пункт B.

def remove_last_em(s):
  return s[:-1] if s and s[-1] == '!' else s
print(remove_last_em("Hi!!!"))

# Пункт С.

def remove_word_with_one_em(s): 
 return ' '.join(word for word in s.split() if word.count('!') != 1)
print(remove_word_with_one_em("Hi! !Hi! Hi!"))