# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-PlaTDFU1riJGSbeyyYlABHam_eDdcP0
"""

number = int(input("Введите число от 0 до 9: "))

def switch_it_up(number):
    d = {
        1:"One", 2:"Two", 3:"Three", 4:"Four", 
        5:"Five", 6:"Six", 7:"Seven", 8:"Eight", 
        9:"Nine", 0:"Zero"
    }
    for i in d.keys():
        if i == number:
            return d[i]
print(switch_it_up(number))