# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-PlaTDFU1riJGSbeyyYlABHam_eDdcP0
"""

#task_1.1.
my_favorite_songs = 'Waste a Moment, Staying\' Alive, A Sorta Fairytale, Start Me Up, New Salvation'
print(my_favorite_songs [0:14], my_favorite_songs [-13:], my_favorite_songs [16:30], my_favorite_songs [-26:-15])

# Задача 1.2.
# Пункт A. 

import random

my_favorite_songs = [
 ['Waste a Moment', 3.03],
 ['New Salvation', 4.02],
 ['Staying\' Alive', 3.40],
 ['Out of Touch', 3.03],
 ['A Sorta Fairytale', 5.28],
 ['Easy', 4.15],
 ['Beautiful Day', 4.04],
 ['Nowhere to Run', 2.58],
 ['In This World', 4.02],
]

k=3
y=[]
total=0


while k != 0:
   x = random.choice(my_favorite_songs)
   k -= 1
   y.append(x)
   print(y)

for i in y:
    #print ("Значение i:", i, "Значение total ", total)
    total += i[1]

print ("Три песни звучат:", total, "минут")

# Задача 1.2.
# Пункт B.

import random
import datetime 

my_favorite_songs_dict = {
    'Waste a Moment': 3.03,
    'New Salvation': 4.02,
    'Staying\' Alive': 3.40,
    'Out of Touch': 3.03,
    'A Sorta Fairytale': 5.28,
    'Easy': 4.15,
    'Beautiful Day': 4.04,
    'Nowhere to Run': 2.58,
    'In This World': 4.02,
}


#1. три случайные песни

song1 = key1, val1 = random.choice(list(my_favorite_songs_dict.items()))
song2 = key2, val2 = random.choice(list(my_favorite_songs_dict.items()))
song3 = key3, val3 = random.choice(list(my_favorite_songs_dict.items()))

songs = song1[0] + ", " + song2[0] + ", " + song3[0]
#print(songs)

#2. сумма трех песен
time = song1[1] + song2[1] + song3[1]
#print(time)


print("Три песни:", songs, "звучат", time, "минут")



#3. перевести сумму трех песен в формат времени