# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tR-bHtpUe4AZCOd7s2OWYT1ljTEaMbjs
"""

import sqlite3

def get_connection():
  connection = sqlite3.connect('teachers.db')
  return connection

def close_connection(connection):
  if connection:
    connection.close()


def get_teacher_detail():
  try:
    connection = get_connection()
    cursor = connection.cursor()
    sqlquery = "SELECT * FROM Students JOIN School ON Students.School_Id=School.School_Id"
    cursor.execute(sqlquery)
    records = cursor.fetchall()
    for row in records:
      print ("ID Студента: ", row[0])
      print ("Имя студента: ", row[1])
      print ("ID школы: ", row[2])
      print ("Название школы: ", row[4], "\n")
    close_connection(connection)
  except (Exception, sqlite3.Error) as error:
    print("Ошибка в получении данных ", error)

get_teacher_detail()