# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-PlaTDFU1riJGSbeyyYlABHam_eDdcP0
"""

# Задача 1.2.
# Пункт A. 

import random

my_favorite_songs = [
 ['Waste a Moment', 3.03],
 ['New Salvation', 4.02],
 ['Staying\' Alive', 3.40],
 ['Out of Touch', 3.03],
 ['A Sorta Fairytale', 5.28],
 ['Easy', 4.15],
 ['Beautiful Day', 4.04],
 ['Nowhere to Run', 2.58],
 ['In This World', 4.02],
]

k=3
y=[]
total=0


while k != 0:
   x = random.choice(my_favorite_songs)
   k -= 1
   y.append(x)
   

for i in y:
    total += i[1]

print ("Три песни:", y, "звучат", total, "минут")



# Задача 1.2.
# Пункт B,C

import random
from datetime import timedelta
import math 

my_favorite_songs_dict = {
    'Waste a Moment': 3.03,
    'New Salvation': 4.02,
    'Staying\' Alive': 3.40,
    'Out of Touch': 3.03,
    'A Sorta Fairytale': 5.28,
    'Easy': 4.15,
    'Beautiful Day': 4.04,
    'Nowhere to Run': 2.58,
    'In This World': 4.02,
}

song1 = key1, val1 = random.choice(list(my_favorite_songs_dict.items()))
song2 = key2, val2 = random.choice(list(my_favorite_songs_dict.items()))
song3 = key3, val3 = random.choice(list(my_favorite_songs_dict.items()))

songs = song1[0] + ", " + song2[0] + ", " + song3[0]

time1 = math.modf(song1 [1])                                    
time2 = math.modf(song2 [1])
time3 = math.modf(song3 [1])

time = timedelta(minutes = time1[1], seconds = time1[0] * 100 ) + timedelta(minutes = time2[1], seconds = time2[0] * 100 ) + timedelta(minutes = time3[1], seconds = time3[0] * 100 )

print("Три песни:", songs, "-", "звучат", time)