# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-PlaTDFU1riJGSbeyyYlABHam_eDdcP0
"""

#task_1.1.
my_favorite_songs = 'Waste a Moment, Staying\' Alive, A Sorta Fairytale, Start Me Up, New Salvation'
print(my_favorite_songs [0:14], my_favorite_songs [-13:], my_favorite_songs [16:30], my_favorite_songs [-26:-15])